### ISSUE TITLE
Redshift user doesn't have update privileges in the subscriptions event table

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/stripe-pipeline#5]
Heya @michael-erasmus! Max pinged me sharing some anomalies in the stripe trials table. [Looking at the raw events table, looks like it stopped adding data last day 28th. ](https://looker.buffer.com/sql/twpstrmppfx6x5)

The deployment is running but has more than 300 restarts. The logs of the previous pods seems to point to some limitation of the `buda` Redshift user.

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) permission denied for relation subscription_events
 [SQL: 'lock buda_stripe.subscription_events'] (Background on this error at: http://sqlalche.me/e/f405)
```

I think the issue could be solved if we give `update` privileges to the `buda` user ([it doesn't have it currently](https://looker.buffer.com/sql/pwkhc3fd5dshwz)). I'll keep this issue updated with the next actions! :smile:

**Comment by davidgasquez** [comment]
I've granted `update` and `delete` privileges in the tables `subscription_events` and `subscription_event_items` to the `buda` user.

```
grant update on table buda_stripe.subscription_events to buda;
grant delete on table buda_stripe.subscription_events to buda;
grant update on table buda_stripe.subscription_event_items to buda;
grant delete on table buda_stripe.subscription_event_items to buda;
```

**Comment by davidgasquez** [comment]
[Seems the events are flowing back into the tables](https://looker.buffer.com/sql/p8kpyqbmbt6gdr)! :tada: 

Tables are also automatically backfilled!

![woah](https://media3.giphy.com/media/ToMjGpnXBTw7vnokxhu/giphy.gif)

**Comment by michael-erasmus** [comment]
Thanks so much for fixing this @davidgasquez! I think this was caused by me earlier while setting up our users for WLM. Good catch!
